library(fixest)
library(modelsummary)
data(mtcars)
model1 <- feols(mpg ~ cyl + disp, data = mtcars)
model2 <- feols(mpg ~ cyl | gear, data = mtcars)
print(coef(model1))
print(coef(model2))
models <- list("M1" = model1, "M2" = model2)
modelsummary(models, output="markdown")
