---
title: "2 Setup for Analysis"
author: "Jonathan"
date: "2025-11-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('/Users/jonat/Library/CloudStorage/OneDrive-ClarkUniversity/CU Courses/Economics Honors Thesis/Scripts')
library(dplyr)
library(ggplot2)
library(tidyverse)
library(readr)
library(stringr)
options(scipen = 999)
```

# Next Steps

1.  DONE. ~~Rework GDP data to be same shape as organization data. So column A = GDP%, column B = Year.~~
    -   Column C = state_GDP% ??
2.  DONE. (In 1b Cleaning Data.R) ~~Merge the GDP data to the organization data. Every single non-profit has to have the corresponding year's GDP variable.~~

## GDP Growth Rate

First, I import the raw GDP data from 1997 - 2024.

```{r}
gdp_data = read_csv('/Users/jonat/Library/CloudStorage/OneDrive-ClarkUniversity/CU Courses/Economics Honors Thesis/Raw Data/SAGDP/SAGDP1__ALL_AREAS_1997_2024.csv')

gdp_data = gdp_data %>%
  filter(Description == "Real GDP (millions of chained 2017 dollars) 1/") %>%
  select(
    state = GeoName,
    `2008`:`2023`) %>%

# Now to turn it into long data format
  pivot_longer(
  cols = `2008`:`2023`,
  names_to = "YEAR",
  values_to = "real_gdp"
) %>%

# Now to do little data cleanup (changing type) and creating percent change column
  mutate(
    YEAR = as.integer(YEAR),
    real_gdp = as.integer(real_gdp),
    gdp_change_percent =  ((real_gdp - lag(real_gdp))/lag(real_gdp))*100
  )
```

## Saving Final Data

```{r}
# 6. Saving
saveRDS(gdp_data, "../Final_Data/gdp_data.rds")
```
